amateur: AHFrun.h File Reference
AHFrun.h File Reference
Header file with all publicly known functions from AHFrun.cpp.
Functions
void AHFrun (unsigned isnap)
Controls execution of AHFstep.
Detailed Description
Header file with all publicly known functions from AHFrun.cpp.
Definition in file AHFrun.h.
Function Documentation
void AHFrun (unsigned isnap)
Controls execution of AHFstep.
Creates the parameter file, invokes AHFstep, moves output files and renames them
Parameters:
isnap snapshot ID
Returns:
void
Definition at line 137 of file AHFrun.cpp.
References CreateAHFParameterFile(), MoveAHFout(), RenameAHFout(), and RunAHFstep().
Referenced by main().