amateur: AnalyzeSnap.cpp File Reference
AnalyzeSnap.cpp File Reference
Analyzes a given snapshot with HaloProperties, for all particle types.
#include <cassert>
#include <fstream>
#include <iostream>
#include <limits>
#include <map>
#include <numeric>
#include <string>
#include <vector>
#include "SystemCharacteristics.h"
#include "DataStruct.h"
#include "ReadGadget.h"
#include "HaloProperties.h"
#include "HDFIO.h"
Functions
std::vector< std::vector
< double > > Vhp_Mass (4)
std::vector< std::vector
< double > > Vhp_LambdaPrime (4)
std::vector< std::vector
< double > > Vhp_J (4)
std::vector< std::vector
< double > > Vhp_EVa (4)
std::vector< std::vector
< double > > Vhp_EVb (4)
std::vector< std::vector
< double > > Vhp_EVc (4)
std::vector< std::vector
< double > > Vhp_Eigenvalues (4)
std::vector< std::vector
< unsigned > > Vhp_HaloParticlesTypesCount (4)
template<typename T>
T byteorder (T v)
void Storeahf (std::fstream &ahfhalos)
void WriteHDF5 (std::string filename, double Boxsize, double Redshift, double HaloTotCount)
void GetOffsets (unsigned *ParticleIDOffsets, unsigned *npart)
void AnalyzeSnap (unsigned isnap)
Variables
std::vector< double > Vhp_PosCM
std::vector< double > Vhp_PosMB
std::vector< double > Vhp_VelCM
std::vector< double > Vhp_Rvir
std::vector< double > Vhp_Mvir
std::vector< unsigned > Vhp_HaloParticlesCount
std::vector< double > Vahf_npart
std::vector< double > Vahf_nvpart
std::vector< double > Vahf_ovdens
std::vector< double > Vahf_sigV
std::vector< double > Vahf_J
std::vector< double > Vahf_EW
std::vector< double > Vahf_EVa
std::vector< double > Vahf_EVb
std::vector< double > Vahf_EVc
std::vector< double > Vahf_Ekin
std::vector< double > Vahf_Epot
std::vector< double > Vahf_xc
Detailed Description
Analyzes a given snapshot with HaloProperties, for all particle types.
Definition in file AnalyzeSnap.cpp.
Function Documentation
void AnalyzeSnap (unsigned isnap)
Definition at line 229 of file AnalyzeSnap.cpp.
References HaloProperties::CenterOnMB(), HaloProperties::CenterVel(), HaloProperties::CleanUnboundExc(), HaloProperties::CleanUnboundSimple(), HaloProperties::ComputeAngularMomentum(), HaloProperties::ComputeCenterVel(), HaloProperties::ComputeCM(), HaloProperties::ComputeLambdaPrime(), HaloProperties::ComputeMajorAxes(), HaloProperties::ComputeMB(), HaloProperties::ComputeTotalMass(), HaloProperties::ComputeVirialProperties(), Folder(), get_particle_number(), GetOffsets(), HDFCreateFile(), HDFCreateGroup(), HDFWriteDataset(), HDFWriteGroupAttribute(), read_gadget_1(), read_gadget_3(), Snaps(), Storeahf(), Vhp_Eigenvalues(), Vhp_EVa(), Vhp_EVb(), Vhp_EVc(), Vhp_HaloParticlesCount, Vhp_HaloParticlesTypesCount(), Vhp_J(), Vhp_LambdaPrime(), Vhp_Mass(), Vhp_Mvir, Vhp_PosCM, Vhp_PosMB, Vhp_Rvir, Vhp_VelCM, and WriteHDF5().
Referenced by main().
template<typename T> T byteorder (T v) [inline]
conversion between little/big endian
Parameters:
v
Returns:
Definition at line 77 of file AnalyzeSnap.cpp.
void GetOffsets (unsigned * ParticleIDOffsets, unsigned * npart)
Definition at line 213 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap().
void Storeahf (std::fstream & ahfhalos)
Definition at line 92 of file AnalyzeSnap.cpp.
References Vahf_Ekin, Vahf_Epot, Vahf_EVa, Vahf_EVb, Vahf_EVc, Vahf_EW, Vahf_J, Vahf_npart, Vahf_nvpart, Vahf_ovdens, Vahf_sigV, and Vahf_xc.
Referenced by AnalyzeSnap().
std::vector< std::vector < double > > Vhp_Eigenvalues (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< std::vector < double > > Vhp_EVa (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< std::vector < double > > Vhp_EVb (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< std::vector < double > > Vhp_EVc (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< std::vector < unsigned > > Vhp_HaloParticlesTypesCount (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< std::vector < double > > Vhp_J (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< std::vector < double > > Vhp_LambdaPrime (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< std::vector < double > > Vhp_Mass (4)
Referenced by AnalyzeSnap(), and WriteHDF5().
void WriteHDF5 (std::string filename, double Boxsize, double Redshift, double HaloTotCount)
Definition at line 164 of file AnalyzeSnap.cpp.
References HDFCreateFile(), HDFCreateGroup(), HDFWriteDataset(), HDFWriteDatasetVector(), HDFWriteGroupAttribute(), Vahf_Ekin, Vahf_Epot, Vahf_EVa, Vahf_EVb, Vahf_EVc, Vahf_EW, Vahf_J, Vahf_npart, Vahf_nvpart, Vahf_ovdens, Vahf_sigV, Vahf_xc, Vhp_Eigenvalues(), Vhp_EVa(), Vhp_EVb(), Vhp_EVc(), Vhp_HaloParticlesCount, Vhp_HaloParticlesTypesCount(), Vhp_J(), Vhp_LambdaPrime(), Vhp_Mass(), Vhp_Mvir, Vhp_PosCM, Vhp_PosMB, Vhp_Rvir, and Vhp_VelCM.
Referenced by AnalyzeSnap().
Variable Documentation
std::vector< double > Vahf_Ekin
Definition at line 68 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_Epot
Definition at line 69 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_EVa
Definition at line 65 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_EVb
Definition at line 66 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_EVc
Definition at line 67 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_EW
Definition at line 64 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_J
Definition at line 63 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_npart
Definition at line 59 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_nvpart
Definition at line 60 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_ovdens
Definition at line 61 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_sigV
Definition at line 62 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< double > Vahf_xc
Definition at line 70 of file AnalyzeSnap.cpp.
Referenced by Storeahf(), and WriteHDF5().
std::vector< unsigned > Vhp_HaloParticlesCount
Definition at line 56 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< double > Vhp_Mvir
Definition at line 46 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< double > Vhp_PosCM
Definition at line 42 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< double > Vhp_PosMB
Definition at line 43 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< double > Vhp_Rvir
Definition at line 45 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap(), and WriteHDF5().
std::vector< double > Vhp_VelCM
Definition at line 44 of file AnalyzeSnap.cpp.
Referenced by AnalyzeSnap(), and WriteHDF5().