amateur: Matrix33 Class Reference
Matrix33 Class Reference
#include <DataStruct.h>
Public Member Functions
Matrix33 ()
Matrix33 (const Matrix33 &m)
~Matrix33 ()
double & operator() (Identifier row, Identifier col)
double operator() (Identifier row, Identifier col) const
Vector3 operator() (Identifier col)
Matrix33 & operator= (Matrix33 const &M)
Matrix33 & operator= (const double &x)
Vector3 operator[] (Identifier col) const
Matrix33 & operator+= (const Matrix33 &m)
Matrix33 & operator-= (const Matrix33 &m)
Matrix33 operator* (const double &x)
Matrix33 operator/ (const double &x)
void set_diag (Vector3 diag)
void Jacobi (Vector3 &lambda, Matrix33 &V, int &nrot)
void Eigen (Vector3 &lambda, std::vector< Vector3 > &V) const
double det (void) const
Vector3 get_invariants (std::vector< Vector3 > &V) const
Protected Attributes
double * m_Data
Detailed Description
Definition at line 97 of file DataStruct.h.
Constructor & Destructor Documentation
Matrix33::Matrix33 ()
Definition at line 254 of file DataStruct.cpp.
References m_Data.
Matrix33::Matrix33 (const Matrix33 & m)
Definition at line 258 of file DataStruct.cpp.
References m_Data.
Matrix33::~Matrix33 ()
Definition at line 264 of file DataStruct.cpp.
References m_Data.
Member Function Documentation
double & Matrix33::operator() (Identifier row, Identifier col)
Definition at line 270 of file DataStruct.cpp.
References m_Data.
double Matrix33::operator() (Identifier row, Identifier col) const
Definition at line 276 of file DataStruct.cpp.
References m_Data.
Vector3 Matrix33::operator() (Identifier col)
Definition at line 282 of file DataStruct.cpp.
Matrix33 & Matrix33::operator= (Matrix33 const & M)
Definition at line 291 of file DataStruct.cpp.
References m_Data.
Matrix33 & Matrix33::operator= (const double & x)
Definition at line 300 of file DataStruct.cpp.
References m_Data.
Vector3 Matrix33::operator[] (Identifier col) const
Definition at line 309 of file DataStruct.cpp.
References m_Data.
Matrix33 & Matrix33::operator+= (const Matrix33 & m)
Definition at line 318 of file DataStruct.cpp.
References m_Data.
Matrix33 & Matrix33::operator-= (const Matrix33 & m)
Definition at line 326 of file DataStruct.cpp.
References m_Data.
Matrix33 Matrix33::operator* (const double & x)
Definition at line 334 of file DataStruct.cpp.
References m_Data.
Matrix33 Matrix33::operator/ (const double & x)
Definition at line 343 of file DataStruct.cpp.
References m_Data.
void Matrix33::set_diag (Vector3 diag)
Definition at line 353 of file DataStruct.cpp.
void Matrix33::Jacobi (Vector3 & lambda, Matrix33 & V, int & nrot)
Definition at line 409 of file DataStruct.cpp.
References ROTATE.
void Matrix33::Eigen (Vector3 & lambda, std::vector< Vector3 > & V) const
Definition at line 361 of file DataStruct.cpp.
References m_Data.
Referenced by HaloProperties::ComputeMajorAxes(), HaloProperties::ComputeMajorAxesReduced(), det(), get_invariants(), and StoreTensorField().
double Matrix33::det (void) const
Definition at line 385 of file DataStruct.cpp.
References Eigen().
Vector3 Matrix33::get_invariants (std::vector< Vector3 > & V) const
Definition at line 396 of file DataStruct.cpp.
References Eigen().
Field Documentation
double* Matrix33::m_Data [protected]
Definition at line 99 of file DataStruct.h.
Referenced by Eigen(), Matrix33(), operator()(), operator*(), operator+=(), operator-=(), operator/(), operator=(), operator[](), and ~Matrix33().
The documentation for this class was generated from the following files:
DataStruct.h
DataStruct.cpp