amateur: ScalarField Class Reference
ScalarField Class Reference
#include <TidalField.h>
Public Member Functions
ScalarField (void)
ScalarField (unsigned nx, unsigned ny, unsigned nz, float dx, int nstencil)
void recreate (unsigned nx, unsigned ny, unsigned nz, float dx, int nstencil)
template<typename T>
float & operator() (T ix, T iy, T iz)
template<typename T>
float operator() (T ix, T iy, T iz) const
int get_xsize (void)
int get_ysize (void)
int get_zsize (void)
float get_dx (void)
int get_stencil (void)
template<typename T>
void put_CIC (unsigned npart, T *coord, float *wpar)
void lookup (float *Coord, unsigned nCoord, std::vector< float > &values)
void lookup (float *Coord, unsigned nCoord, float ll, unsigned N, std::vector< float > &values)
template<typename T>
T get_NGP (T *coord)
float get_CIC (float coordx, float coordy, float coordz)
void ChooseStencil (void)
void diff2atCIC (float *Coord, unsigned nPoints, std::vector< Matrix33 > &t_ij)
float diff1 (int ix, int iy, int iz, int i)
float diff2 (int ix, int iy, int iz, int i, int j)
Protected Member Functions
void diff_primitive (ScalarField *, bool bStagger=false)
Protected Attributes
array3 m_data
float m_dx
unsigned m_nx
unsigned m_ny
unsigned m_nz
int m_nstencil
int m_nsten2
float * m_pStencil1
float * m_pStencil2
Detailed Description
Definition at line 134 of file TidalField.h.
Constructor & Destructor Documentation
ScalarField::ScalarField (void) [inline]
Definition at line 150 of file TidalField.h.
ScalarField::ScalarField (unsigned nx, unsigned ny, unsigned nz, float dx, int nstencil) [inline]
Definition at line 153 of file TidalField.h.
Member Function Documentation
void ScalarField::diff_primitive (ScalarField * , bool bStagger = false) [protected]
void ScalarField::recreate (unsigned nx, unsigned ny, unsigned nz, float dx, int nstencil) [inline]
Definition at line 159 of file TidalField.h.
Referenced by PoissonSolver< nstencil >::solve().
template<typename T> float& ScalarField::operator() (T ix, T iy, T iz) [inline]
Definition at line 170 of file TidalField.h.
template<typename T> float ScalarField::operator() (T ix, T iy, T iz) const [inline]
Definition at line 175 of file TidalField.h.
int ScalarField::get_xsize (void) [inline]
Definition at line 179 of file TidalField.h.
Referenced by PoissonSolver< nstencil >::solve().
int ScalarField::get_ysize (void) [inline]
Definition at line 182 of file TidalField.h.
Referenced by PoissonSolver< nstencil >::solve().
int ScalarField::get_zsize (void) [inline]
Definition at line 185 of file TidalField.h.
Referenced by PoissonSolver< nstencil >::solve().
float ScalarField::get_dx (void) [inline]
Definition at line 188 of file TidalField.h.
Referenced by PoissonSolver< nstencil >::solve().
int ScalarField::get_stencil (void) [inline]
Definition at line 191 of file TidalField.h.
Referenced by PoissonSolver< nstencil >::solve().
template<typename T> void ScalarField::put_CIC (unsigned npart, T * coord, float * wpar) [inline]
Definition at line 153 of file TidalField.cpp.
References m_data, m_nx, m_ny, and m_nz.
Referenced by TidalField().
void ScalarField::lookup (float * Coord, unsigned nCoord, std::vector< float > & values) [inline]
Definition at line 201 of file TidalField.h.
void ScalarField::lookup (float * Coord, unsigned nCoord, float ll, unsigned N, std::vector< float > & values) [inline]
Definition at line 208 of file TidalField.h.
template<typename T> T ScalarField::get_NGP (T * coord) [inline]
Definition at line 217 of file TidalField.h.
float ScalarField::get_CIC (float coordx, float coordy, float coordz) [inline]
Definition at line 226 of file TidalField.h.
Referenced by TidalField().
void ScalarField::ChooseStencil (void)
Definition at line 94 of file TidalField.cpp.
References m_nstencil, m_pStencil1, m_pStencil2, stencil11_1, stencil11_2, stencil3_1, stencil3_2, stencil5_1, stencil5_2, stencil7_1, stencil7_2, stencil9_1, and stencil9_2.
Referenced by diff2atCIC().
void ScalarField::diff2atCIC (float * Coord, unsigned nPoints, std::vector< Matrix33 > & t_ij)
diff2atCIC
Parameters:
Coord,: list of coordinates
nPoints,: number of points in Coord where we want to know the tensor
t_ij,: tensor
Returns:
void
Definition at line 222 of file TidalField.cpp.
References ChooseStencil(), diff2(), m_nx, m_ny, and m_nz.
Referenced by TidalField().
float ScalarField::diff1 (int ix, int iy, int iz, int i) [inline]
Definition at line 261 of file TidalField.h.
float ScalarField::diff2 (int ix, int iy, int iz, int i, int j) [inline]
Definition at line 279 of file TidalField.h.
Referenced by diff2atCIC().
Field Documentation
array3 ScalarField::m_data [protected]
Definition at line 138 of file TidalField.h.
Referenced by put_CIC().
float ScalarField::m_dx [protected]
Definition at line 141 of file TidalField.h.
unsigned ScalarField::m_nx [protected]
Definition at line 142 of file TidalField.h.
Referenced by diff2atCIC(), and put_CIC().
unsigned ScalarField::m_ny [protected]
Definition at line 142 of file TidalField.h.
Referenced by diff2atCIC(), and put_CIC().
unsigned ScalarField::m_nz [protected]
Definition at line 142 of file TidalField.h.
Referenced by diff2atCIC(), and put_CIC().
int ScalarField::m_nstencil [protected]
Definition at line 143 of file TidalField.h.
Referenced by ChooseStencil().
int ScalarField::m_nsten2 [protected]
Definition at line 143 of file TidalField.h.
float* ScalarField::m_pStencil1 [protected]
Definition at line 145 of file TidalField.h.
Referenced by ChooseStencil().
float * ScalarField::m_pStencil2 [protected]
Definition at line 145 of file TidalField.h.
Referenced by ChooseStencil().
The documentation for this class was generated from the following files:
TidalField.h
TidalField.cpp