amateur: OctTreeNode Class Reference
OctTreeNode Class Reference
#include <OctTree.h>
Public Member Functions
OctTreeNode (std::vector< PseudoBody > *Bodies)
OctTreeNode (std::vector< PseudoBody > &Bodies, real min_size)
~OctTreeNode ()
real traverse (const real &x, const real &y, const real &z, const real &theta, const real &plumsoft)
Protected Member Functions
void partition (const std::vector< PseudoBody > &All, std::vector< PseudoBody > ***Bodies)
void getBoundingBox (const std::vector< PseudoBody > &bodies, real &xc, real &yc, real &zc, real &l)
Protected Attributes
OctTreeNode ** m_subnodes
PseudoBody m_body
real m_xc
real m_yc
real m_zc
real m_l
bool m_bleaf
Detailed Description
Definition at line 476 of file OctTree.h.
Constructor & Destructor Documentation
OctTreeNode::OctTreeNode (std::vector< PseudoBody > * Bodies) [inline]
Definition at line 544 of file OctTree.h.
References getBoundingBox(), m_l, m_xc, m_yc, and m_zc.
Referenced by OctTreeNode().
OctTreeNode::OctTreeNode (std::vector< PseudoBody > & Bodies, real min_size) [inline]
Definition at line 554 of file OctTree.h.
References getBoundingBox(), m_bleaf, m_l, m_subnodes, m_xc, m_yc, m_zc, OctTreeNode(), and partition().
OctTreeNode::~OctTreeNode () [inline]
Definition at line 614 of file OctTree.h.
References m_subnodes.
Member Function Documentation
void OctTreeNode::partition (const std::vector< PseudoBody > & All, std::vector< PseudoBody > *** Bodies) [inline, protected]
Definition at line 488 of file OctTree.h.
References m_xc, m_yc, and m_zc.
Referenced by OctTreeNode().
void OctTreeNode::getBoundingBox (const std::vector< PseudoBody > & bodies, real & xc, real & yc, real & zc, real & l) [inline, protected]
Definition at line 512 of file OctTree.h.
Referenced by OctTreeNode().
real OctTreeNode::traverse (const real & x, const real & y, const real & z, const real & theta, const real & plumsoft) [inline]
Definition at line 626 of file OctTree.h.
References EPS, PseudoBody::getmass(), PseudoBody::getx(), PseudoBody::getxx(), PseudoBody::getxy(), PseudoBody::getxz(), PseudoBody::gety(), PseudoBody::getyy(), PseudoBody::getyz(), PseudoBody::getz(), PseudoBody::getzz(), m_bleaf, m_body, m_l, m_subnodes, and SPLINEQ().
Referenced by HaloProperties::ComputePotentialTree(), and HaloProperties::ComputePotentialTreeExc().
Field Documentation
OctTreeNode** OctTreeNode::m_subnodes [protected]
Definition at line 479 of file OctTree.h.
Referenced by OctTreeNode(), traverse(), and ~OctTreeNode().
PseudoBody OctTreeNode::m_body [protected]
Definition at line 481 of file OctTree.h.
Referenced by traverse().
real OctTreeNode::m_xc [protected]
Definition at line 484 of file OctTree.h.
Referenced by OctTreeNode(), and partition().
real OctTreeNode::m_yc [protected]
Definition at line 484 of file OctTree.h.
Referenced by OctTreeNode(), and partition().
real OctTreeNode::m_zc [protected]
Definition at line 484 of file OctTree.h.
Referenced by OctTreeNode(), and partition().
real OctTreeNode::m_l [protected]
Definition at line 485 of file OctTree.h.
Referenced by OctTreeNode(), and traverse().
bool OctTreeNode::m_bleaf [protected]
Definition at line 486 of file OctTree.h.
Referenced by OctTreeNode(), and traverse().
The documentation for this class was generated from the following file:
OctTree.h