amateur: list< T > Class Template Reference
list< T > Class Template Reference
#include <MySTL.h>
Public Member Functions
list ()
list (const list &L)
void reverse ()
void swap (list &x)
list & operator= (const list &x)
~list ()
void clear ()
void push_front (const T &x)
void push_back (const T &x)
void pop_front ()
bool empty ()
T & front ()
const T & front () const
T & back ()
const T & back () const
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator erase (iterator x)
iterator insert (iterator x, const T &y)
void rotate (iterator x)
void splice (list< T > &other)
Identifier size (void)
Data Structures
class const_iterator
class iterator
struct Node
Detailed Description
template<class T>
class list< T >
Definition at line 95 of file MySTL.h.
Constructor & Destructor Documentation
template<class T> list< T >::list () [inline]
Definition at line 196 of file MySTL.h.
template<class T> list< T >::list (const list< T > & L) [inline]
Definition at line 198 of file MySTL.h.
References list< T >::begin(), list< T >::end(), list< T >::push_front(), and list< T >::reverse().
template<class T> list< T >::~list () [inline]
Definition at line 236 of file MySTL.h.
References list< T >::clear().
Member Function Documentation
template<class T> void list< T >::reverse () [inline]
Definition at line 207 of file MySTL.h.
References list< T >::empty().
Referenced by list< T >::list().
template<class T> void list< T >::swap (list< T > & x) [inline]
Definition at line 223 of file MySTL.h.
References list< T >::m_n, and list< T >::m_node.
Referenced by list< T >::operator=().
template<class T> list& list< T >::operator= (const list< T > & x) [inline]
Definition at line 229 of file MySTL.h.
References list< T >::swap().
template<class T> void list< T >::clear (void) [inline]
Definition at line 238 of file MySTL.h.
Referenced by list< T >::~list().
template<class T> void list< T >::push_front (const T & x) [inline]
Definition at line 254 of file MySTL.h.
References list< T >::begin(), and list< T >::insert().
Referenced by list< T >::list().
template<class T> void list< T >::push_back (const T & x) [inline]
Definition at line 258 of file MySTL.h.
References list< T >::end(), and list< T >::insert().
template<class T> void list< T >::pop_front () [inline]
Definition at line 262 of file MySTL.h.
References list< T >::begin(), and list< T >::erase().
template<class T> bool list< T >::empty () [inline]
Definition at line 267 of file MySTL.h.
Referenced by list< T >::reverse().
template<class T> T& list< T >::front () [inline]
Definition at line 269 of file MySTL.h.
References list< T >::begin().
template<class T> const T& list< T >::front () const [inline]
Definition at line 270 of file MySTL.h.
References list< T >::begin().
template<class T> T& list< T >::back () [inline]
Definition at line 271 of file MySTL.h.
template<class T> const T& list< T >::back () const [inline]
Definition at line 272 of file MySTL.h.
template<class T> iterator list< T >::begin () [inline]
Definition at line 274 of file MySTL.h.
Referenced by convertlists(), list< T >::front(), list< T >::list(), list< T >::pop_front(), and list< T >::push_front().
template<class T> iterator list< T >::end () [inline]
Definition at line 276 of file MySTL.h.
Referenced by convertlists(), list< T >::erase(), list< T >::list(), list< T >::push_back(), and list< T >::rotate().
template<class T> const_iterator list< T >::begin () const [inline]
Definition at line 278 of file MySTL.h.
template<class T> const_iterator list< T >::end () const [inline]
Definition at line 282 of file MySTL.h.
template<class T> iterator list< T >::erase (iterator x) [inline]
Definition at line 287 of file MySTL.h.
References list< T >::end(), and list< T >::iterator::m_rep.
Referenced by list< T >::pop_front().
template<class T> iterator list< T >::insert (iterator x, const T & y) [inline]
Definition at line 301 of file MySTL.h.
References list< T >::iterator::m_rep.
Referenced by list< T >::push_back(), and list< T >::push_front().
template<class T> void list< T >::rotate (iterator x) [inline]
Definition at line 312 of file MySTL.h.
References list< T >::end(), and list< T >::iterator::m_rep.
template<class T> void list< T >::splice (list< T > & other) [inline]
Definition at line 337 of file MySTL.h.
References list< T >::m_n, and list< T >::m_node.
template<class T> Identifier list< T >::size (void) [inline]
Definition at line 354 of file MySTL.h.
The documentation for this class was generated from the following file:
MySTL.h