amateur: kDTreeNode Class Reference
kDTreeNode Class Reference
#include <OctTree.h>
Public Member Functions
~kDTreeNode ()
kDTreeNode (std::vector< PseudoBody > *Bodies)
kDTreeNode (std::vector< PseudoBody > &Bodies)
real traverse (const real &x, const real &y, const real &z, const real &theta, const real &plumsoft)
Protected Member Functions
void partition (std::vector< PseudoBody > &All, std::vector< PseudoBody > **bleft, std::vector< PseudoBody > **bright)
void getBoundingBox (const std::vector< PseudoBody > &bodies)
Protected Attributes
kDTreeNode * m_nleft
kDTreeNode * m_nright
PseudoBody m_body
real m_l
bool m_bleaf
int m_axis
Detailed Description
Definition at line 224 of file OctTree.h.
Constructor & Destructor Documentation
kDTreeNode::~kDTreeNode () [inline]
Definition at line 303 of file OctTree.h.
References m_nleft, and m_nright.
kDTreeNode::kDTreeNode (std::vector< PseudoBody > * Bodies) [inline]
Definition at line 310 of file OctTree.h.
References getBoundingBox().
Referenced by kDTreeNode().
kDTreeNode::kDTreeNode (std::vector< PseudoBody > & Bodies) [inline]
Definition at line 323 of file OctTree.h.
References getBoundingBox(), kDTreeNode(), m_axis, m_bleaf, m_nleft, m_nright, and partition().
Member Function Documentation
void kDTreeNode::partition (std::vector< PseudoBody > & All, std::vector< PseudoBody > ** bleft, std::vector< PseudoBody > ** bright) [inline, protected]
Definition at line 235 of file OctTree.h.
References PseudoBody::getx(), PseudoBody::gety(), PseudoBody::getz(), m_axis, and m_body.
Referenced by kDTreeNode().
void kDTreeNode::getBoundingBox (const std::vector< PseudoBody > & bodies) [inline, protected]
Definition at line 266 of file OctTree.h.
References m_l.
Referenced by kDTreeNode().
real kDTreeNode::traverse (const real & x, const real & y, const real & z, const real & theta, const real & plumsoft) [inline]
Definition at line 385 of file OctTree.h.
References EPS, PseudoBody::getmass(), PseudoBody::getx(), PseudoBody::getxx(), PseudoBody::getxy(), PseudoBody::getxz(), PseudoBody::gety(), PseudoBody::getyy(), PseudoBody::getyz(), PseudoBody::getz(), PseudoBody::getzz(), m_bleaf, m_body, m_l, m_nleft, m_nright, and SPLINEQ().
Field Documentation
kDTreeNode* kDTreeNode::m_nleft [protected]
Definition at line 226 of file OctTree.h.
Referenced by kDTreeNode(), traverse(), and ~kDTreeNode().
kDTreeNode * kDTreeNode::m_nright [protected]
Definition at line 226 of file OctTree.h.
Referenced by kDTreeNode(), traverse(), and ~kDTreeNode().
PseudoBody kDTreeNode::m_body [protected]
Definition at line 228 of file OctTree.h.
Referenced by partition(), and traverse().
real kDTreeNode::m_l [protected]
Definition at line 230 of file OctTree.h.
Referenced by getBoundingBox(), and traverse().
bool kDTreeNode::m_bleaf [protected]
Definition at line 232 of file OctTree.h.
Referenced by kDTreeNode(), and traverse().
int kDTreeNode::m_axis [protected]
Definition at line 233 of file OctTree.h.
Referenced by kDTreeNode(), and partition().
The documentation for this class was generated from the following file:
OctTree.h