amateur: HDFIO.h File Reference
HDFIO.h File Reference
Some templated C++ HDF5 front-end functions.
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <sstream>
#include <typeinfo>
#include <vector>
#include "hdf5.h"
Data Structures
class HDFException
Functions
template<typename T>
hid_t GetDataType (void)
bool DoesFileExist (std::string Filename)
void AssertFileOpen (std::string Filename)
void HDFCreateFile (std::string Filename)
template<typename T>
void HDFReadVector (const std::string Filename, const std::string ObjName, std::vector< T > &Data)
void HDFGetDatasetExtent (const std::string Filename, const std::string ObjName, std::vector< int > &Extent)
template<typename T>
void HDFReadDataset (const std::string Filename, const std::string ObjName, std::vector< T > &Data)
template<typename T>
void HDFReadSelect (const std::string Filename, const std::string ObjName, const std::vector< unsigned > &ii, std::vector< T > &Data)
template<typename T>
void HDFReadVectorSelect (const std::string Filename, const std::string ObjName, const std::vector< unsigned > &ii, std::vector< T > &Data)
template<typename T>
void HDFReadVectorSlab (const std::string Filename, const std::string ObjName, unsigned nStart, unsigned nCount, std::vector< T > &Data)
template<typename T>
void HDFReadDatasetSlab (const std::string Filename, const std::string ObjName, unsigned nStart, unsigned nCount, std::vector< T > &Data)
template<typename T>
void HDFReadGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, T &Data)
template<typename T>
void HDFReadGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, std::vector< T > &Data)
template<typename T>
void HDFWriteDataset (const std::string Filename, const std::string ObjName, const std::vector< T > &Data)
template<typename T>
void HDFWriteDataset2D (const std::string Filename, const std::string ObjName, const std::vector< std::vector< T > > &Data)
template<typename T>
void HDFWriteDatasetVector (const std::string Filename, const std::string ObjName, const std::vector< T > &Data)
void HDFCreateGroup (const std::string Filename, const std::string GroupName)
template<typename T>
void HDFWriteGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, const std::vector< T > &Data)
template<typename T>
void HDFWriteGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, T Data)
template<>
void HDFWriteGroupAttribute< std::string > (const std::string Filename, const std::string GroupName, const std::string ObjName, std::string Data)
Detailed Description
Some templated C++ HDF5 front-end functions.
Definition in file HDFIO.h.
Function Documentation
void AssertFileOpen (std::string Filename) [inline]
Definition at line 72 of file HDFIO.h.
References DoesFileExist().
bool DoesFileExist (std::string Filename) [inline]
Definition at line 62 of file HDFIO.h.
Referenced by AssertFileOpen().
template<typename T> hid_t GetDataType (void) [inline]
Definition at line 38 of file HDFIO.h.
void HDFCreateFile (std::string Filename) [inline]
Definition at line 80 of file HDFIO.h.
Referenced by AnalyzeSnap(), ExtractSnap(), TidalField(), and WriteHDF5().
void HDFCreateGroup (const std::string Filename, const std::string GroupName) [inline]
Definition at line 709 of file HDFIO.h.
Referenced by AnalyzeSnap(), ExtractSnap(), and WriteHDF5().
void HDFGetDatasetExtent (const std::string Filename, const std::string ObjName, std::vector< int > & Extent) [inline]
Definition at line 94 of file HDFIO.h.
template<typename T> void HDFReadDataset (const std::string Filename, const std::string ObjName, std::vector< T > & Data) [inline]
Definition at line 143 of file HDFIO.h.
Referenced by HDFReadVector(), and TidalField().
template<typename T> void HDFReadDatasetSlab (const std::string Filename, const std::string ObjName, unsigned nStart, unsigned nCount, std::vector< T > & Data) [inline]
Definition at line 432 of file HDFIO.h.
template<typename T> void HDFReadGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, std::vector< T > & Data) [inline]
Definition at line 544 of file HDFIO.h.
template<typename T> void HDFReadGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, T & Data) [inline]
Definition at line 500 of file HDFIO.h.
Referenced by TidalField().
template<typename T> void HDFReadSelect (const std::string Filename, const std::string ObjName, const std::vector< unsigned > & ii, std::vector< T > & Data) [inline]
Definition at line 216 of file HDFIO.h.
template<typename T> void HDFReadVector (const std::string Filename, const std::string ObjName, std::vector< T > & Data) [inline]
Definition at line 88 of file HDFIO.h.
References HDFReadDataset().
Referenced by TidalField().
template<typename T> void HDFReadVectorSelect (const std::string Filename, const std::string ObjName, const std::vector< unsigned > & ii, std::vector< T > & Data) [inline]
Definition at line 277 of file HDFIO.h.
template<typename T> void HDFReadVectorSlab (const std::string Filename, const std::string ObjName, unsigned nStart, unsigned nCount, std::vector< T > & Data) [inline]
Definition at line 367 of file HDFIO.h.
template<typename T> void HDFWriteDataset (const std::string Filename, const std::string ObjName, const std::vector< T > & Data) [inline]
Definition at line 605 of file HDFIO.h.
Referenced by AnalyzeSnap(), ExtractSnap(), TidalField(), and WriteHDF5().
template<typename T> void HDFWriteDataset2D (const std::string Filename, const std::string ObjName, const std::vector< std::vector< T > > & Data) [inline]
Definition at line 633 of file HDFIO.h.
Referenced by StoreTensorField().
template<typename T> void HDFWriteDatasetVector (const std::string Filename, const std::string ObjName, const std::vector< T > & Data) [inline]
Definition at line 674 of file HDFIO.h.
Referenced by ExtractSnap(), StoreTensorField(), and WriteHDF5().
template<typename T> void HDFWriteGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, T Data) [inline]
Definition at line 750 of file HDFIO.h.
template<typename T> void HDFWriteGroupAttribute (const std::string Filename, const std::string GroupName, const std::string ObjName, const std::vector< T > & Data) [inline]
Definition at line 721 of file HDFIO.h.
Referenced by AnalyzeSnap(), ExtractSnap(), and WriteHDF5().
template<> void HDFWriteGroupAttribute< std::string > (const std::string Filename, const std::string GroupName, const std::string ObjName, std::string Data) [inline]