amateur: NFWFit.h File Reference
NFWFit.h File Reference
Fit of a Navarro-Frenk-White potential.
#include <vector>
#include <cassert>
#include <gsl/gsl_vector.h>
#include <gsl/gsl_blas.h>
#include <gsl/gsl_multifit_nlin.h>
#include <gsl/gsl_errno.h>
#include <iostream>
Data Structures
struct fitdata
struct fitdata_fix
Functions
void print_state (size_t iter, gsl_multifit_fdfsolver *s)
int NFW_f (const gsl_vector *p, void *data, gsl_vector *f)
int NFW_fix_f (const gsl_vector *p, void *data, gsl_vector *f)
int NFW_df (const gsl_vector *p, void *data, gsl_matrix *J)
int NFW_fix_df (const gsl_vector *p, void *data, gsl_matrix *J)
int NFW_fdf (const gsl_vector *x, void *data, gsl_vector *f, gsl_matrix *J)
int NFW_fix_fdf (const gsl_vector *x, void *data, gsl_vector *f, gsl_matrix *J)
int NFW_fit (const std::vector< double > &r, const std::vector< double > &rho, const std::vector< double > &sigma_rho, double deltac0, double rs0, double &deltac, double &edeltac, double &rs, double &ers)
int NFW_fix_fit (const std::vector< double > &r, const std::vector< double > &rho, const std::vector< double > &sigma_rho, double rvir, double mvir, double rs0, double &rs, double &ers)
Detailed Description
Fit of a Navarro-Frenk-White potential.
Definition in file NFWFit.h.
Function Documentation
int NFW_df (const gsl_vector * p, void * data, gsl_matrix * J)
Definition at line 117 of file NFWFit.h.
References fitdata::n, fitdata::sigma, and fitdata::x.
Referenced by NFW_fdf(), and NFW_fit().
int NFW_f (const gsl_vector * p, void * data, gsl_vector * f)
Definition at line 73 of file NFWFit.h.
References fitdata::n, fitdata::sigma, fitdata::x, and fitdata::y.
Referenced by NFW_fdf(), and NFW_fit().
int NFW_fdf (const gsl_vector * x, void * data, gsl_vector * f, gsl_matrix * J)
Definition at line 194 of file NFWFit.h.
References NFW_df(), and NFW_f().
Referenced by NFW_fit().
int NFW_fit (const std::vector< double > & r, const std::vector< double > & rho, const std::vector< double > & sigma_rho, double deltac0, double rs0, double & deltac, double & edeltac, double & rs, double & ers)
Definition at line 208 of file NFWFit.h.
References fitdata_fix::n, NFW_df(), NFW_f(), NFW_fdf(), print_state(), and fitdata::x.
Referenced by HaloProperties::FitNFWProfile2().
int NFW_fix_df (const gsl_vector * p, void * data, gsl_matrix * J)
Definition at line 171 of file NFWFit.h.
References fitdata_fix::mvir, fitdata_fix::n, fitdata_fix::rvir, fitdata_fix::sigma, and fitdata_fix::x.
Referenced by NFW_fix_fdf(), and NFW_fix_fit().
int NFW_fix_f (const gsl_vector * p, void * data, gsl_vector * f)
Definition at line 93 of file NFWFit.h.
References fitdata_fix::mvir, fitdata_fix::n, fitdata_fix::rvir, fitdata_fix::sigma, fitdata_fix::x, and fitdata_fix::y.
Referenced by NFW_fix_fdf(), and NFW_fix_fit().
int NFW_fix_fdf (const gsl_vector * x, void * data, gsl_vector * f, gsl_matrix * J)
Definition at line 201 of file NFWFit.h.
References NFW_fix_df(), and NFW_fix_f().
Referenced by NFW_fix_fit().
int NFW_fix_fit (const std::vector< double > & r, const std::vector< double > & rho, const std::vector< double > & sigma_rho, double rvir, double mvir, double rs0, double & rs, double & ers)
Definition at line 288 of file NFWFit.h.
References fitdata::n, NFW_fix_df(), NFW_fix_f(), NFW_fix_fdf(), print_state(), and fitdata_fix::x.
Referenced by HaloProperties::FitNFWProfile1(), and HaloProperties::FitNFWProfile200().
void print_state (size_t iter, gsl_multifit_fdfsolver * s)
Definition at line 67 of file NFWFit.h.
Referenced by NFW_fit(), and NFW_fix_fit().