amateur: ReadGadget.h File Reference
ReadGadget.h File Reference
All publicly known functions from ReadGadget.c and template instantiations.
#include <string>
Functions
void swap_Nbyte (char *data, int n, int m)
size_t my_fread (void *ptr, size_t size, size_t nmemb, FILE *stream)
int find_block (FILE *fd, char *label)
template<typename T>
int read_gadget_1 (T *data, std::string label, FILE *fd)
template<typename T>
int read_gadget_3 (T *data, std::string label, FILE *fd)
int read_gadget_head (int *npart, double *massarr, double *time, double *redshift, FILE *fd)
void get_particle_number (std::string filename, unsigned *id_min, unsigned *id_max, double *masses, unsigned *npart, unsigned &ntot, double &redshift, double &boxsize)
Detailed Description
All publicly known functions from ReadGadget.c and template instantiations.
Definition in file ReadGadget.h.
Function Documentation
int find_block (FILE * fd, char * label)
void get_particle_number (std::string filename, unsigned * id_min, unsigned * id_max, double * masses, unsigned * npart, unsigned & ntot, double & redshift, double & boxsize)
Definition at line 218 of file ReadGadget.c.
References read_gadget_1(), and read_gadget_head().
Referenced by AnalyzeSnap(), and ExtractSnap().
size_t my_fread (void * ptr, size_t size, size_t nmemb, FILE * stream)
Definition at line 29 of file ReadGadget.c.
Referenced by find_block(), read_gadget_1(), read_gadget_3(), and read_gadget_head().
template<typename T> int read_gadget_1 (T * data, std::string label, FILE * fd) [inline]
read a 1D array
Parameters:
data
label
fd
Returns:
Definition at line 159 of file ReadGadget.c.
References find_block(), my_fread(), SKIP, and swap_Nbyte().
Referenced by AnalyzeSnap(), ExtractSnap(), and get_particle_number().
template<typename T> int read_gadget_3 (T * data, std::string label, FILE * fd) [inline]
read a 3D array
Parameters:
data
label
fd
Returns:
Definition at line 188 of file ReadGadget.c.
References find_block(), my_fread(), SKIP, and swap_Nbyte().
Referenced by AnalyzeSnap(), and ExtractSnap().
int read_gadget_head (int * npart, double * massarr, double * time, double * redshift, FILE * fd)
void swap_Nbyte (char * data, int n, int m)