amateur: SnapReadHDF5.h File Reference
SnapReadHDF5.h File Reference
Functions
int snap_read (void)
Function Documentation
int snap_read (void)
Definition at line 23 of file SnapReadHDF5.h.
References HDFCreateFile(), HDFCreateGroup(), HDFReadDatasetSlab(), HDFReadVectorSlab(), HDFWriteDataset(), and HDFWriteDatasetVector().