amateur: SubhaloMatch.h File Reference
SubhaloMatch.h File Reference
All publicly known functions of SubhaloMatch.cpp.
Functions
void SubhaloMatch (unsigned isnap)
Detailed Description
All publicly known functions of SubhaloMatch.cpp.
Definition in file SubhaloMatch.h.
Function Documentation
void SubhaloMatch (unsigned isnap)
Definition at line 61 of file SubhaloMatch.cpp.
References Folder(), GetLineNumber(), GetMtreeFile(), Snaps(), and WriteMtree2File().
Referenced by main().