amateur: SystemCharacteristics.h File Reference
SystemCharacteristics.h File Reference
All publicly known functions from SystemCharacteristics.cpp.
#include <string>
Functions
void RunCommand (std::string command)
std::string IntToString (int intValue)
std::string Folder (std::string where)
std::string Snaps (unsigned SnapNo)
unsigned GetLineNumber (std::string filename)
Detailed Description
All publicly known functions from SystemCharacteristics.cpp.
Definition in file SystemCharacteristics.h.
Function Documentation
std::string Folder (std::string where)
Returns the paths to all important folders.
Parameters:
where,: which folder? allowed: amd, snap, amateur, output
Returns:
std::string full path
Definition at line 124 of file SystemCharacteristics.cpp.
Referenced by AnalyzeSnap(), CreateAHFParameterFile(), CreateHaloTrackerParameterFile(), CreateMergeParameterFile(), ExtractSnap(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), RenameAHFout(), RewriteParticleNumbers(), RunAHFstep(), RunHaloTracker(), RunMergerTree(), RunOwnMergerTree(), SubhaloMatch(), TidalField(), and WrapperParticleNumbers().
unsigned GetLineNumber (std::string filename)
count the lines of a given file
Parameters:
filename,: path to the file
Returns:
unsigned number of lines
Definition at line 46 of file SystemCharacteristics.cpp.
Referenced by SubhaloMatch().
std::string IntToString (int intValue)
Convert an integer into a string.
Parameters:
intValue,: integer to be converted
Returns:
std::string of that integer value
Definition at line 105 of file SystemCharacteristics.cpp.
References itoa().
Referenced by TidalField().
void RunCommand (std::string command)
Definition at line 36 of file SystemCharacteristics.cpp.
Referenced by ExtractSnap(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), RenameAHFout(), RunAHFstep(), RunHaloTracker(), and RunMergerTree().
std::string Snaps (unsigned SnapNo)
Returns the full path to an AMATEUR snapshot
Parameters:
SnapNo,: ID of snapshot
Returns:
std::string full_path
Definition at line 151 of file SystemCharacteristics.cpp.
Referenced by AnalyzeSnap(), CreateAHFParameterFile(), CreateHaloTrackerParameterFile(), CreateMergeParameterFile(), ExtractSnap(), HelpUser(), main(), MoveAHFout(), MoveHaloTrackerOutput(), MoveMergeOut(), RenameAHFout(), RewriteParticleNumbers(), RunOwnMergerTree(), SubhaloMatch(), TidalField(), and WrapperParticleNumbers().