amateur: TidalField.cpp File Reference
TidalField.cpp File Reference
Implements the -t: Computation of the tidal field.
#include <unistd.h>
#include <sstream>
#include "TidalField.h"
#include "HDFIO.h"
#include "PoissonSolver.h"
#include "SystemCharacteristics.h"
Functions
bool DoesFileExist (char *filename)
void StoreTensorField (std::string filename, unsigned nPoints, const std::vector< float > &coordinates, const std::vector< Matrix33 > &aTensorField, float SmoothingMassScale)
void TidalField (std::string snaphdf5, unsigned N, double Radius, std::string extrahdf5, std::string tensorhdf5)
void TidalField (unsigned isnap, int N, double Radius)
Variables
const float G_const = 43011.7902
float stencil11_1 [11]
float stencil11_2 [11]
float stencil9_1 [9]
float stencil9_2 [9]
float stencil7_1 [7]
float stencil7_2 [7]
float stencil5_1 [5] = { 0.0833333333, -0.6666666667, 0.0, 0.6666666667, -0.0833333333 }
float stencil5_2 [5] = { -0.0833333333, 1.3333333333, -2.5, 1.3333333333, -0.0833333333 }
float stencil3_1 [3]
float stencil3_2 [3]
Detailed Description
Implements the -t: Computation of the tidal field.
Definition in file TidalField.cpp.
Function Documentation
bool DoesFileExist (char * filename)
Definition at line 135 of file TidalField.cpp.
void StoreTensorField (std::string filename, unsigned nPoints, const std::vector< float > & coordinates, const std::vector< Matrix33 > & aTensorField, float SmoothingMassScale)
store tensor field to HDF5
Parameters:
filename,: path to output file
nPoints,: number of points
coordinates,: evaluation points
aTensorField,: tensor field that should be evaluated
SmoothingMassScale,: smoothing scale
Definition at line 308 of file TidalField.cpp.
References Matrix33::Eigen(), HDFWriteDataset2D(), and HDFWriteDatasetVector().
Referenced by TidalField().
void TidalField (unsigned isnap, int N, double Radius)
Definition at line 479 of file TidalField.cpp.
References Folder(), IntToString(), Snaps(), and TidalField().
void TidalField (std::string snaphdf5, unsigned N, double Radius, std::string extrahdf5, std::string tensorhdf5)
computes the tidal field from a given mass distribution
Parameters:
snaphdf5,: a snapshot file, converted by AnalyzeSnap
N,: the length of the density mesh
Radius,: the length scale used for smoothing
extrahdf5,: file containing the CMs of the halos
tensorhdf5,: output file for the tensor components
Returns:
void
Definition at line 361 of file TidalField.cpp.
References ScalarField::diff2atCIC(), G_const, ScalarField::get_CIC(), HDFCreateFile(), HDFReadDataset(), HDFReadGroupAttribute(), HDFReadVector(), HDFWriteDataset(), ScalarField::put_CIC(), PoissonSolver< nstencil >::solve(), and StoreTensorField().
Referenced by main(), and TidalField().
Variable Documentation
const float G_const = 43011.7902
Definition at line 21 of file TidalField.cpp.
Referenced by TidalField().
float stencil11_1[11]
Initial value:
 { -7.9365079365e-04,
                            9.9206349206e-03,
                            -5.9523809524e-02,
                            2.3809523810e-01,
                            -8.3333333333e-01,
                            0.0,
                            8.3333333333e-01,
                            -2.3809523810e-01,
                            5.9523809524e-02,
                            -9.9206349206e-03,
                            7.9365079365e-04 }
Definition at line 23 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil11_2[11]
Initial value:
 { 3.1746031746e-04,
                            -4.9603174603e-03,
                            3.9682539683e-02,
                            -2.3809523810e-01,
                            1.6666666667e+00,
                            -2.9272222222e+00,
                            1.6666666667e+00,
                            -2.3809523810e-01,
                            3.9682539683e-02,
                            -4.9603174603e-03,
                            3.1746031746e-04 }
Definition at line 34 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil3_1[3]
Initial value:
 { -0.5,
                          0.0,
                          0.5 }
Definition at line 81 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil3_2[3]
Initial value:
 { 1.0,
                          -2.0,
                          1.0 }
Definition at line 84 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil5_1[5] = { 0.0833333333, -0.6666666667, 0.0, 0.6666666667, -0.0833333333 }
Definition at line 78 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil5_2[5] = { -0.0833333333, 1.3333333333, -2.5, 1.3333333333, -0.0833333333 }
Definition at line 79 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil7_1[7]
Initial value:
 {  -0.0166666667,
                0.1500000000,
                -0.7500000000,
                0.0,
                0.7500000000,
                -0.1500000000,
                0.0166666667 }
Definition at line 63 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil7_2[7]
Initial value:
 { 0.0111111111,
                          -0.1500000000,
                          1.5000000000,
                          -2.7222222222,
                          1.5000000000,
                          -0.1500000000,
                          0.0111111111 }
Definition at line 70 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil9_1[9]
Initial value:
 { 3.5714285714e-03,
                          -3.8095238095e-02,
                          0.2000000000,
                          -0.8000000000,
                          0.0,
                          0.8000000000,
                          -0.2000000000,
                          3.8095238095e-02,
                          -3.5714285714e-03 }
Definition at line 45 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().
float stencil9_2[9]
Initial value:
 { -1.7857142857e-03,
                          2.5396825397e-02,
                          -2.0000000000e-01,
                          1.6000000000e+00,
                          -2.8472222222e+00,
                          1.6000000000e+00,
                          -2.0000000000e-01,
                          2.5396825397e-02,
                          -1.7857142857e-03 }
Definition at line 54 of file TidalField.cpp.
Referenced by ScalarField::ChooseStencil().