amateur: TidalField.h File Reference
TidalField.h File Reference
Class declarations for invocation of -t.
#include <math.h>
#include "DataStruct.h"
Data Structures
class GreensFunction< nOrder >
class array3
class ScalarField
Defines
#define EPS_ACC 1.0e-6
Functions
void TidalField (unsigned isnap, int N, double Radius)
Detailed Description
Class declarations for invocation of -t.
Definition in file TidalField.h.
Define Documentation
#define EPS_ACC 1.0e-6
Definition at line 32 of file TidalField.h.
Function Documentation
void TidalField (unsigned isnap, int N, double Radius)
Definition at line 479 of file TidalField.cpp.
References Folder(), IntToString(), Snaps(), and TidalField().